'use client';

import React, { useState, useEffect, useRef } from 'react';
import { GoogleGenAI } from '@google/genai';
import { motion, AnimatePresence } from 'motion/react';
import {
  Moon, Sun, Mic, MicOff, Send, Share2, MapPin, 
  CheckCircle, ExternalLink, Key, ChevronDown, ChevronUp,
  MessageSquare, Calendar, CheckSquare, Search, Info, Check, Link as LinkIcon
} from 'lucide-react';
import { cn } from '@/lib/utils';

// --- CONSTANTS ---
const SYSTEM_PROMPT = "You are Election Saathi, India's friendliest election guide. Answer questions about voter registration, EVM voting, election timelines, polling booths, ECI rules. Use simple language, numbered steps, and bullet points. Never give political opinions or endorse candidates. Direct users to eci.gov.in for official information.";

const QUICK_ACTIONS = [
  "How do I register to vote?",
  "What documents do I need on voting day?",
  "Explain the election timeline",
  "How does EVM voting work?",
  "How to find my polling booth?",
  "How to file an election complaint?"
];

const TIMELINE_STAGES = [
  { title: "1. Election Announcement", detail: "The ECI announces the schedule, marked by the Model Code of Conduct coming into effect." },
  { title: "2. Voter List Finalization", detail: "Electoral rolls are updated. Last chance to verify your name on the voters list." },
  { title: "3. Nomination Filing", detail: "Candidates file their nomination papers and affidavits before the Returning Officer." },
  { title: "4. Scrutiny of Nominations", detail: "The RO examines the filed nominations to ensure they meet all legal requirements." },
  { title: "5. Withdrawal of Candidature", detail: "Candidates who wish to withdraw their nominations can do so by the specified date." },
  { title: "6. Election Campaign", detail: "Candidates campaign. Campaigning stops 48 hours before the end of polling." },
  { title: "7. Polling Day", detail: "Voting from 7am to 6pm. EPIC card or approved alternate photo ID is required to vote." },
  { title: "8. Vote Counting", detail: "EVMs are opened and votes are counted in the presence of candidates/agents." },
  { title: "9. Result Declaration", detail: "The Returning Officer declares the final results and issues the certificate of election." },
  { title: "10. Oath Taking", detail: "Elected representatives take the oath of office." }
];

const CHECKLIST_ITEMS = [
  "Have EPIC card or valid photo ID",
  "Know exact polling booth address",
  "Verified name on voter roll",
  "Fully charged mobile phone (keep outside booth)",
  "Plan to arrive early to avoid lines",
  "Not carrying any campaign material",
  "Ready to get finger inked",
  "Know to check VVPAT slip after voting"
];

const ECI_LINKS = [
  { label: "Check registration", url: "https://voters.eci.gov.in", desc: "voters.eci.gov.in" },
  { label: "Download EPIC card", url: "https://nvsp.in", desc: "nvsp.in" },
  { label: "File complaint", url: "https://eci.gov.in/complaints", desc: "eci.gov.in/complaints" },
  { label: "Candidate info", url: "https://affidavit.eci.gov.in", desc: "affidavit.eci.gov.in" }
];

const STATES = [
  "Andaman and Nicobar Islands", "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar",
  "Chandigarh", "Chhattisgarh", "Dadra and Nagar Haveli and Daman and Diu", "Delhi", "Goa",
  "Gujarat", "Haryana", "Himachal Pradesh", "Jammu and Kashmir", "Jharkhand", "Karnataka",
  "Kerala", "Ladakh", "Lakshadweep", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya",
  "Mizoram", "Nagaland", "Odisha", "Puducherry", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu",
  "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal"
];

const QUIZ_QUESTIONS = [
  { q: "What is the minimum voting age in India?", options: ["16", "18", "21", "25"], answer: "18" },
  { q: "Who conducts the Lok Sabha elections in India?", options: ["State Election Commission", "President of India", "Election Commission of India", "Supreme Court"], answer: "Election Commission of India" },
  { q: "What does EVM stand for?", options: ["Electronic Voting Machine", "Electoral Voting Method", "Electronic Voter Machine", "Election Validation Machine"], answer: "Electronic Voting Machine" },
  { q: "What is the VVPAT?", options: ["A new voting machine", "A paper slip generated by EVM to verify the vote", "An ID card", "A political party"], answer: "A paper slip generated by EVM to verify the vote" },
  { q: "Which of these is NOT a valid ID for voting if you don't have an EPIC card?", options: ["Passport", "Driving License", "Ration Card (without photo)", "Aadhaar Card"], answer: "Ration Card (without photo)" }
];

interface Message {
  role: 'user' | 'model';
  text: string;
}

export default function ElectionSaathi() {
  const [mounted, setMounted] = useState(false);
  const [isDark, setIsDark] = useState(false);
  const [apiKey, setApiKey] = useState("");
  const [isKeyValid, setIsKeyValid] = useState(false);
  const [isValidatingKey, setIsValidatingKey] = useState(false);
  const [keyError, setKeyError] = useState("");
  const validationTimeout = useRef<NodeJS.Timeout | null>(null);

  // Layout Refs for Scrolling
  const chatRef = useRef<HTMLDivElement>(null);
  const timelineRef = useRef<HTMLDivElement>(null);
  const boothRef = useRef<HTMLDivElement>(null);
  const chatContentRef = useRef<HTMLDivElement>(null);

  // Chat State
  const [messages, setMessages] = useState<Message[]>([
    { role: 'model', text: 'Namaste! I am Election Saathi. How can I help you with the election process today?' }
  ]);
  const [inputValue, setInputValue] = useState("");
  const [isSending, setIsSending] = useState(false);
  const [isListening, setIsListening] = useState(false);

  // Feature States
  const [expandedStage, setExpandedStage] = useState<number | null>(null);
  const [quizIndex, setQuizIndex] = useState(0);
  const [quizScore, setQuizScore] = useState(0);
  const [quizFinished, setQuizFinished] = useState(false);
  const [quizFeedback, setQuizFeedback] = useState("");
  const [pincode, setPincode] = useState("");
  const [checklist, setChecklist] = useState<boolean[]>(new Array(8).fill(false));
  const [age, setAge] = useState("");
  const [state, setState] = useState("");
  const [eligibilityMsg, setEligibilityMsg] = useState<{title: string, desc: string, ok: boolean} | null>(null);
  const [countdown, setCountdown] = useState({ d: 0, h: 0, m: 0, s: 0 });

  // Init
  useEffect(() => {
    setMounted(true);
    // Theme
    const savedTheme = localStorage.getItem('saathi_theme');
    if (savedTheme === 'dark') {
      setIsDark(true);
      document.documentElement.classList.add('dark');
    }
    // API Key
    const savedKey = window.localStorage.getItem('gemini_api_key') || process.env.NEXT_PUBLIC_GEMINI_API_KEY;
    if (savedKey) {
      setApiKey(savedKey);
      setIsValidatingKey(true);
      const ai = new GoogleGenAI({ apiKey: savedKey });
      ai.models.generateContent({
        model: "gemini-3.1-flash-lite-preview",
        contents: "hi",
        config: { maxOutputTokens: 1 }
      }).then(() => {
        setIsKeyValid(true);
        setIsValidatingKey(false);
      }).catch(() => {
        setIsKeyValid(false);
        setKeyError("Invalid API Key");
        setIsValidatingKey(false);
      });
    }
    // Checklist
    const savedChecklist = localStorage.getItem('saathi_checklist');
    if (savedChecklist) {
      setChecklist(JSON.parse(savedChecklist));
    }
  }, []);

  // Countdown timer
  useEffect(() => {
    const targetDate = new Date("2025-10-01T00:00:00").getTime();
    const interval = setInterval(() => {
      const now = new Date().getTime();
      const distance = targetDate - now;
      if (distance < 0) return clearInterval(interval);
      setCountdown({
        d: Math.floor(distance / (1000 * 60 * 60 * 24)),
        h: Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60)),
        m: Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60)),
        s: Math.floor((distance % (1000 * 60)) / 1000)
      });
    }, 1000);
    return () => clearInterval(interval);
  }, []);

  // Scroll to bottom of chat
  useEffect(() => {
    if (chatContentRef.current) {
      chatContentRef.current.scrollTop = chatContentRef.current.scrollHeight;
    }
  }, [messages, isSending]);

  // Handlers
  const toggleTheme = () => {
    if (isDark) {
      document.documentElement.classList.remove('dark');
      localStorage.setItem('saathi_theme', 'light');
      setIsDark(false);
    } else {
      document.documentElement.classList.add('dark');
      localStorage.setItem('saathi_theme', 'dark');
      setIsDark(true);
    }
  };

  const handleKeyChange = (key: string) => {
    setApiKey(key);
    if (!key) {
      localStorage.removeItem('gemini_api_key');
      setIsKeyValid(false);
      setKeyError("");
      if (validationTimeout.current) clearTimeout(validationTimeout.current);
      return;
    }
    
    if (validationTimeout.current) clearTimeout(validationTimeout.current);
    validationTimeout.current = setTimeout(async () => {
      setIsValidatingKey(true);
      setKeyError("");
      setIsKeyValid(false);
      try {
        const ai = new GoogleGenAI({ apiKey: key });
        await ai.models.generateContent({
          model: "gemini-3.1-flash-lite-preview",
          contents: "hi",
          config: { maxOutputTokens: 1 }
        });
        setIsKeyValid(true);
        setKeyError("");
        localStorage.setItem('gemini_api_key', key);
      } catch (e: any) {
        console.error("API Key Validation Error:", e);
        setIsKeyValid(false);
        setKeyError("Invalid API Key");
      } finally {
        setIsValidatingKey(false);
      }
    }, 1000);
  };

  // Chat
  const handleSendMessage = async (text: string) => {
    if (!text.trim()) return;
    const finalKey = apiKey || process.env.NEXT_PUBLIC_GEMINI_API_KEY;
    if (!finalKey || !isKeyValid) {
      alert("Please enter a valid Gemini API key at the top to chat.");
      return;
    }

    const newMessages = [...messages, { role: 'user' as const, text }];
    setMessages(newMessages);
    setInputValue('');
    setIsSending(true);

    try {
      const ai = new GoogleGenAI({ apiKey: finalKey });
      // Build conversation history for context
      const contents = newMessages.map(m => ({
        role: m.role,
        parts: [{ text: m.text }]
      }));
      
      const response = await ai.models.generateContent({
        model: "gemini-3.1-flash-lite-preview",
        contents: contents,
        config: {
          systemInstruction: SYSTEM_PROMPT,
          temperature: 0.7,
        }
      });
      
      const reply = response.text || "Sorry, I couldn't formulate a response.";
      setMessages(prev => [...prev, { role: 'model', text: reply }]);
    } catch (e: any) {
      console.error(e);
      setMessages(prev => [...prev, { role: 'model', text: "Sorry, an error occurred. Please check your API key and try again." }]);
      setKeyError("Invalid API Key or API error.");
    } finally {
      setIsSending(false);
    }
  };

  const handleVoiceInput = () => {
    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (!SpeechRecognition) {
      alert("Speech recognition is not supported in your browser.");
      return;
    }
    const recognition = new SpeechRecognition();
    recognition.lang = 'en-IN';
    recognition.continuous = false;
    
    recognition.onstart = () => setIsListening(true);
    recognition.onresult = (event: any) => {
      const transcript = event.results[0][0].transcript;
      handleSendMessage(transcript);
    };
    recognition.onerror = () => setIsListening(false);
    recognition.onend = () => setIsListening(false);
    
    recognition.start();
  };

  const handleActionClick = (q: string) => {
    chatRef.current?.scrollIntoView({ behavior: 'smooth' });
    handleSendMessage(q);
  };

  const shareToWhatsApp = (text: string) => {
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
  };

  // Eligibility
  const checkEligibility = () => {
    if (!age || !state) return;
    const ageNum = parseInt(age);
    if (ageNum >= 18) {
      setEligibilityMsg({
        ok: true,
        title: "You are Eligible!",
        desc: `Since you are ${ageNum}, you can vote in ${state}. Make sure your name is registered on the electoral roll at voters.eci.gov.in.`
      });
    } else {
      setEligibilityMsg({
        ok: false,
        title: "Not Yet Eligible",
        desc: `You need to be 18 to vote. You will be eligible in ${18 - ageNum} year(s).`
      });
    }
  };

  // Checklist
  const toggleChecklist = (i: number) => {
    const next = [...checklist];
    next[i] = !next[i];
    setChecklist(next);
    localStorage.setItem('saathi_checklist', JSON.stringify(next));
  };
  const allChecked = checklist.every(Boolean) && checklist.length > 0;

  // Quiz
  const handleQuizAnswer = (opt: string) => {
    const q = QUIZ_QUESTIONS[quizIndex];
    if (opt === q.answer) {
      setQuizScore(s => s + 1);
      setQuizFeedback("Correct!");
      setTimeout(() => proceedNextQuestion(), 1000);
    } else {
      setQuizFeedback("Incorrect. Asking Election Saathi for an explanation...");
      handleActionClick(`I answered "${opt}" to "${q.q}" but the correct answer is "${q.answer}". Can you explain why in a short paragraph?`);
      setTimeout(() => proceedNextQuestion(), 3000);
    }
  };
  const proceedNextQuestion = () => {
    setQuizFeedback("");
    if (quizIndex < QUIZ_QUESTIONS.length - 1) {
      setQuizIndex(i => i + 1);
    } else {
      setQuizFinished(true);
    }
  };
  const resetQuiz = () => {
    setQuizIndex(0);
    setQuizScore(0);
    setQuizFinished(false);
    setQuizFeedback("");
  };

  if (!mounted) return null;

  return (
    <div className="min-h-screen bg-white dark:bg-zinc-950 text-zinc-900 dark:text-zinc-50 font-sans transition-colors duration-300">
      
      {/* 1. TRICOLOR BAR */}
      <div className="h-1 w-full flex">
        <div className="h-full w-1/3 bg-[#FF671F]" />
        <div className="h-full w-1/3 bg-white" />
        <div className="h-full w-1/3 bg-[#046A38]" />
      </div>

      {/* NAVBAR */}
      <nav className="sticky top-0 z-50 bg-white/80 dark:bg-zinc-950/80 backdrop-blur-md border-b border-zinc-200 dark:border-zinc-800">
        <div className="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <CheckCircle className="w-6 h-6 text-[#FF671F]" />
            <h1 className="text-xl font-bold tracking-tight">
              <span className="text-[#FF671F]">Election</span> Saathi
            </h1>
          </div>
          <div className="hidden md:flex gap-6 text-sm font-medium">
            <button onClick={() => chatRef.current?.scrollIntoView({behavior:'smooth'})} className="hover:text-[#FF671F] transition-colors">Chat</button>
            <button onClick={() => timelineRef.current?.scrollIntoView({behavior:'smooth'})} className="hover:text-[#FF671F] transition-colors">Timeline</button>
            <button onClick={() => boothRef.current?.scrollIntoView({behavior:'smooth'})} className="hover:text-[#FF671F] transition-colors">Booth Info</button>
          </div>
          <div className="flex items-center gap-3">
            <div className="relative flex flex-col group">
              <div className="flex items-center bg-zinc-100 dark:bg-zinc-900 px-3 py-1.5 rounded-full border border-zinc-200 dark:border-zinc-800">
                <Key className="w-4 h-4 mr-2 text-zinc-500" />
                <input 
                  type="password"
                  placeholder="Gemini API Key"
                  value={apiKey}
                  onChange={(e) => handleKeyChange(e.target.value)}
                  className="bg-transparent text-xs outline-none w-24 focus:w-48 transition-all dark:placeholder-zinc-600"
                />
                {isValidatingKey ? (
                  <div className="w-4 h-4 ml-1 border-2 border-zinc-300 border-t-zinc-600 rounded-full animate-spin"></div>
                ) : isKeyValid ? (
                  <Check className="w-4 h-4 ml-1 text-green-600 dark:text-green-400" />
                ) : null}
              </div>
              {keyError && (
                <div className="absolute top-12 right-0 bg-red-50 dark:bg-red-900/20 text-red-600 dark:text-red-400 border border-red-200 dark:border-red-800 text-[10px] px-2 py-1 rounded whitespace-nowrap shadow-sm">
                  {keyError}
                </div>
              )}
            </div>
            <button onClick={toggleTheme} aria-label="Toggle Dark Mode" className="p-2 rounded-full hover:bg-zinc-100 dark:hover:bg-zinc-900 transition-colors">
              {isDark ? <Sun className="w-5 h-5" /> : <Moon className="w-5 h-5" />}
            </button>
          </div>
        </div>
      </nav>

      {/* HERO SECTION */}
      <section className="pt-24 pb-16 px-4 text-center max-w-4xl mx-auto">
        <motion.div initial={{opacity:0, y:20}} animate={{opacity:1, y:0}} transition={{duration:0.6}}>
          <h2 className="text-5xl md:text-6xl font-extrabold tracking-tight mb-6">
            Meet <span className="text-[#FF671F]">Election Saathi</span>
          </h2>
          <p className="text-xl text-zinc-600 dark:text-zinc-400 mb-10">
            Your guide to India&apos;s election process — step by step.
          </p>
          
          <div className="flex flex-wrap justify-center gap-3">
            {QUICK_ACTIONS.map((action, i) => (
              <motion.button 
                key={i}
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                onClick={() => handleActionClick(action)}
                className="bg-zinc-100 dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 hover:border-[#FF671F] dark:hover:border-[#FF671F] px-4 py-2 rounded-full text-sm font-medium transition-colors"
                aria-label={`Ask: ${action}`}
              >
                {action}
              </motion.button>
            ))}
          </div>
        </motion.div>
      </section>

      <div className="max-w-7xl mx-auto px-4 pb-24 grid grid-cols-1 lg:grid-cols-12 gap-8">
        
        {/* LEFT COLUMN: Chat & Quiz */}
        <div className="lg:col-span-7 space-y-8">
          
          {/* AI CHAT BOX */}
          <div ref={chatRef} className="bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-3xl overflow-hidden shadow-sm flex flex-col h-[600px]">
            <div className="p-4 bg-zinc-50 dark:bg-zinc-950 border-b border-zinc-200 dark:border-zinc-800 flex items-center">
              <MessageSquare className="w-5 h-5 mr-3 text-[#FF671F]" />
              <h3 className="font-semibold">Chat with Saathi</h3>
            </div>
            
            <div ref={chatContentRef} className="flex-1 overflow-y-auto p-4 space-y-4" role="log" aria-live="polite">
              {messages.map((m, i) => (
                <motion.div 
                  initial={{opacity:0, y:10}} animate={{opacity:1, y:0}}
                  key={i} 
                  className={cn(
                    "flex flex-col max-w-[85%]",
                    m.role === 'user' ? "ml-auto items-end" : "mr-auto items-start"
                  )}
                >
                  <div className={cn(
                    "px-4 py-3 rounded-2xl whitespace-pre-wrap",
                    m.role === 'user' 
                      ? "bg-[#FF671F] text-white rounded-tr-sm" 
                      : "bg-zinc-100 dark:bg-zinc-800 rounded-tl-sm"
                  )}>
                    {m.text}
                  </div>
                  {m.role === 'model' && (
                    <button 
                      onClick={() => shareToWhatsApp(m.text)}
                      className="mt-1 flex items-center text-xs text-zinc-500 hover:text-green-600 transition-colors"
                      aria-label="Share on WhatsApp"
                    >
                      <Share2 className="w-3 h-3 mr-1" /> Share
                    </button>
                  )}
                </motion.div>
              ))}
              {isSending && (
                <div className="flex items-center gap-1 text-zinc-400 bg-zinc-100 dark:bg-zinc-800 px-4 py-3 rounded-2xl rounded-tl-sm w-fit">
                  <div className="w-2 h-2 rounded-full bg-current animate-bounce" style={{animationDelay:'0ms'}}/>
                  <div className="w-2 h-2 rounded-full bg-current animate-bounce" style={{animationDelay:'150ms'}}/>
                  <div className="w-2 h-2 rounded-full bg-current animate-bounce" style={{animationDelay:'300ms'}}/>
                </div>
              )}
            </div>
            
            <div className="p-4 bg-white dark:bg-zinc-900 border-t border-zinc-200 dark:border-zinc-800">
              <div className="relative flex items-center">
                <input
                  type="text"
                  value={inputValue}
                  onChange={e => setInputValue(e.target.value)}
                  onKeyDown={e => e.key === 'Enter' && handleSendMessage(inputValue)}
                  placeholder="Ask any question about elections..."
                  className="w-full bg-zinc-100 dark:bg-zinc-800 border-transparent focus:border-[#FF671F] focus:ring-0 rounded-full pl-6 pr-24 py-3 outline-none transition-all dark:placeholder-zinc-500"
                />
                <div className="absolute right-2 flex items-center gap-1">
                  <button 
                    onClick={handleVoiceInput}
                    className={cn("p-2 rounded-full transition-colors", isListening ? "bg-red-100 text-red-600 animate-pulse" : "text-zinc-500 hover:bg-zinc-200 dark:hover:bg-zinc-700")}
                    aria-label="Voice input"
                  >
                    {isListening ? <Mic className="w-5 h-5" /> : <MicOff className="w-5 h-5" />}
                  </button>
                  <button 
                    onClick={() => handleSendMessage(inputValue)}
                    className="bg-[#046A38] hover:bg-[#03522b] text-white p-2 rounded-full transition-colors disabled:opacity-50"
                    disabled={!inputValue.trim() || isSending}
                    aria-label="Send message"
                  >
                    <Send className="w-5 h-5" />
                  </button>
                </div>
              </div>
            </div>
          </div>

          {/* QUIZ SECTION */}
          <div className="bg-zinc-50 dark:bg-zinc-900/50 border border-zinc-200 dark:border-zinc-800 rounded-3xl p-6">
            <h3 className="text-xl font-bold mb-4 flex items-center"><CheckSquare className="w-5 h-5 mr-2 text-[#046A38]"/> Test Your Knowledge</h3>
            {!quizFinished ? (
              <div className="space-y-4">
                <p className="font-medium text-lg">{quizIndex + 1}. {QUIZ_QUESTIONS[quizIndex].q}</p>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  {QUIZ_QUESTIONS[quizIndex].options.map(opt => (
                     <button
                       key={opt}
                       onClick={() => handleQuizAnswer(opt)}
                       className="p-3 bg-white dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 rounded-xl text-left hover:border-[#FF671F] transition-colors"
                     >
                       {opt}
                     </button>
                  ))}
                </div>
                {quizFeedback && <p className={cn("text-sm font-medium", quizFeedback.includes("Correct") ? "text-green-600" : "text-[#FF671F]")}>{quizFeedback}</p>}
              </div>
            ) : (
              <div className="text-center py-6">
                <p className="text-2xl font-bold mb-2">You scored {quizScore} / {QUIZ_QUESTIONS.length}</p>
                <button onClick={resetQuiz} className="text-[#FF671F] font-medium underline">Try Again</button>
              </div>
            )}
          </div>
          
        </div>

        {/* RIGHT COLUMN: Utilities */}
        <div className="lg:col-span-5 space-y-8">
          
          {/* ELIGIBILITY CHECKER */}
          <div className="bg-[#FF671F]/5 border border-[#FF671F]/20 rounded-3xl p-6">
            <h3 className="font-bold text-lg mb-4 text-[#FF671F]">Am I Eligible to Vote?</h3>
            <div className="space-y-4">
              <div className="flex gap-4">
                <input 
                  type="number" 
                  placeholder="Age" 
                  value={age} 
                  onChange={e => setAge(e.target.value)} 
                  className="w-24 px-4 py-2 rounded-xl border border-zinc-200 dark:border-zinc-700 bg-white dark:bg-zinc-900 outline-none focus:border-[#FF671F]"
                />
                <select 
                  value={state} 
                  onChange={e => setState(e.target.value)}
                  className="flex-1 px-4 py-2 rounded-xl border border-zinc-200 dark:border-zinc-700 bg-white dark:bg-zinc-900 outline-none focus:border-[#FF671F]"
                >
                  <option value="">Select State</option>
                  {STATES.map(s => <option key={s} value={s}>{s}</option>)}
                </select>
              </div>
              <button 
                onClick={checkEligibility} 
                className="w-full bg-[#FF671F] text-white font-medium py-2 rounded-xl hover:bg-[#e55c1b] transition-colors"
              >
                Check Eligibility
              </button>
              {eligibilityMsg && (
                <div className={cn("p-4 rounded-xl text-sm border", eligibilityMsg.ok ? "bg-green-50 border-green-200 text-green-900 dark:bg-green-900/20 dark:text-green-100" : "bg-red-50 border-red-200 text-red-900 dark:bg-red-900/20 dark:text-red-100")}>
                  <strong>{eligibilityMsg.title}</strong><br/>
                  {eligibilityMsg.desc}
                </div>
              )}
            </div>
          </div>

          {/* CHECKLIST */}
          <div className="bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-3xl p-6 shadow-sm">
            <h3 className="font-bold text-lg mb-4 flex items-center"><CheckCircle className="w-5 h-5 mr-2 text-[#046A38]"/> Election Day Checklist</h3>
            <div className="space-y-3">
              {CHECKLIST_ITEMS.map((item, i) => (
                <label key={i} className="flex items-start gap-3 cursor-pointer group">
                  <div className={cn(
                    "w-5 h-5 shrink-0 rounded border flex items-center justify-center transition-colors mt-0.5",
                    checklist[i] ? "bg-[#046A38] border-[#046A38]" : "border-zinc-300 dark:border-zinc-600 group-hover:border-[#046A38]"
                  )}>
                    {checklist[i] && <Check className="w-3.5 h-3.5 text-white" />}
                  </div>
                  <span className={cn("text-sm", checklist[i] && "line-through text-zinc-400")}>{item}</span>
                </label>
              ))}
            </div>
            {allChecked && (
              <motion.div initial={{opacity:0, scale:0.95}} animate={{opacity:1, scale:1}} className="mt-6 bg-[#046A38] text-white p-3 rounded-xl text-center font-medium">
                ✅ You are ready to vote!
              </motion.div>
            )}
          </div>

          {/* COUNTDOWN */}
          <div className="bg-zinc-900 text-white rounded-3xl p-6 text-center shadow-lg relative overflow-hidden">
            <div className="absolute inset-0 opacity-20 pointer-events-none" style={{ backgroundImage: 'radial-gradient(circle at center, #FF671F 0%, transparent 70%)' }}></div>
            <p className="text-sm font-medium uppercase tracking-wider text-zinc-400 mb-2">Next Major Election</p>
            <h4 className="text-xl font-bold mb-4">Bihar Assembly 2025</h4>
            <div className="grid grid-cols-4 gap-2">
              <div className="bg-white/10 rounded-lg py-2 backdrop-blur-sm"><div className="text-2xl font-mono">{countdown.d}</div><div className="text-[10px] uppercase text-zinc-400">Days</div></div>
              <div className="bg-white/10 rounded-lg py-2 backdrop-blur-sm"><div className="text-2xl font-mono">{countdown.h}</div><div className="text-[10px] uppercase text-zinc-400">Hours</div></div>
              <div className="bg-white/10 rounded-lg py-2 backdrop-blur-sm"><div className="text-2xl font-mono">{countdown.m}</div><div className="text-[10px] uppercase text-zinc-400">Mins</div></div>
              <div className="bg-white/10 rounded-lg py-2 backdrop-blur-sm"><div className="text-2xl font-mono">{countdown.s}</div><div className="text-[10px] uppercase text-zinc-400">Secs</div></div>
            </div>
          </div>

          {/* QUICK LINKS */}
          <div className="bg-zinc-50 dark:bg-zinc-900/50 border border-zinc-200 dark:border-zinc-800 rounded-3xl p-6">
            <h3 className="font-bold text-lg mb-4 flex items-center"><LinkIcon className="w-5 h-5 mr-2 text-zinc-500"/> ECI Quick Links</h3>
            <div className="space-y-3">
              {ECI_LINKS.map(link => (
                <a key={link.url} href={link.url} target="_blank" rel="noopener noreferrer" className="flex items-center justify-between p-3 bg-white dark:bg-zinc-800 rounded-xl hover:shadow-sm border border-transparent hover:border-zinc-200 dark:hover:border-zinc-700 transition-all group">
                  <div>
                    <div className="font-medium text-sm group-hover:text-[#FF671F] transition-colors">{link.label}</div>
                    <div className="text-xs text-zinc-500">{link.desc}</div>
                  </div>
                  <ExternalLink className="w-4 h-4 text-zinc-400 group-hover:text-[#FF671F]" />
                </a>
              ))}
            </div>
          </div>

        </div>
      </div>

      {/* TIMELINE SECTION */}
      <section ref={timelineRef} className="bg-zinc-50 dark:bg-zinc-900 border-y border-zinc-200 dark:border-zinc-800 py-20">
        <div className="max-w-4xl mx-auto px-4">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold flex items-center justify-center"><Calendar className="w-8 h-8 mr-3 text-[#FF671F]"/> Election Timeline</h2>
            <p className="text-zinc-600 dark:text-zinc-400 mt-2">The standard 10-stage process of Indian elections.</p>
          </div>
          
          <div className="space-y-4 relative before:absolute before:inset-0 before:ml-5 before:-translate-x-px md:before:mx-auto md:before:translate-x-0 before:h-full before:w-0.5 before:bg-zinc-200 dark:before:bg-zinc-800">
            {TIMELINE_STAGES.map((stage, i) => (
              <div key={i} className="relative flex items-center justify-between md:justify-normal md:odd:flex-row-reverse group is-active">
                <div className="flex items-center justify-center w-10 h-10 rounded-full border-4 border-white dark:border-zinc-900 bg-[#FF671F] text-white shadow shrink-0 md:order-1 md:group-odd:-translate-x-1/2 md:group-even:translate-x-1/2 cursor-pointer z-10" onClick={() => setExpandedStage(expandedStage === i ? null : i)}>
                  {i + 1}
                </div>
                <div className="w-[calc(100%-4rem)] md:w-[calc(50%-2.5rem)] p-4 rounded-2xl bg-white dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 shadow-sm cursor-pointer hover:scale-[1.02] hover:border-[#FF671F] hover:shadow-md transition-all duration-200" onClick={() => setExpandedStage(expandedStage === i ? null : i)}>
                  <div className="flex items-center justify-between">
                    <h4 className="font-bold text-sm md:text-base">{stage.title}</h4>
                    {expandedStage === i ? <ChevronUp className="w-4 h-4 text-zinc-400"/> : <ChevronDown className="w-4 h-4 text-zinc-400"/>}
                  </div>
                  <AnimatePresence>
                    {expandedStage === i && (
                      <motion.div initial={{height:0, opacity:0}} animate={{height:'auto', opacity:1}} exit={{height:0, opacity:0}} className="overflow-hidden">
                        <p className="text-sm text-zinc-600 dark:text-zinc-400 mt-2">{stage.detail}</p>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* BOOTH INFO & MAPS */}
      <section ref={boothRef} className="py-20 max-w-7xl mx-auto px-4">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
          <div>
            <h2 className="text-3xl font-bold mb-6 flex items-center"><MapPin className="w-8 h-8 mr-3 text-[#046A38]"/> Booth Info</h2>
            <div className="space-y-6 text-lg text-zinc-700 dark:text-zinc-300">
              <p>Find your polling booth easily before election day. Standard voting hours are <strong className="text-zinc-900 dark:text-white bg-zinc-100 dark:bg-zinc-800 px-2 py-1 rounded">7:00 AM to 6:00 PM</strong>.</p>
              
              <motion.div 
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6 }}
                className="bg-blue-50/50 dark:bg-blue-900/10 border border-blue-100 dark:border-blue-900/30 p-5 rounded-2xl flex items-start gap-3"
              >
                <Info className="w-6 h-6 text-blue-500 shrink-0 mt-0.5" />
                <div>
                  <h4 className="font-bold text-blue-900 dark:text-blue-100">Documents Needed</h4>
                  <p className="text-sm text-blue-800 dark:text-blue-200 mt-1">Carry your EPIC (Voter ID) card. If you don&apos;t have it, you can use any of the 12 approved alternate photo IDs like Aadhaar, PAN Card, Driving License, or Passport.</p>
                </div>
              </motion.div>

              <div>
                <p className="mb-3 font-medium">Search for your booth quickly:</p>
                <div className="flex gap-3">
                  <input 
                    type="text" 
                    value={pincode}
                    onChange={e => setPincode(e.target.value)}
                    placeholder="Enter your Pincode..."
                    className="flex-1 px-4 py-3 rounded-xl border border-zinc-200 dark:border-zinc-700 bg-white dark:bg-zinc-900 outline-none focus:border-[#046A38]"
                  />
                  <button 
                    onClick={() => {
                      if(pincode) window.open(`https://www.google.com/maps/search/polling+booth+near+${pincode}+India`, '_blank')
                    }}
                    className="bg-[#046A38] text-white px-6 py-3 rounded-xl hover:bg-[#03522b] font-medium flex items-center gap-2 transition-colors"
                  >
                    <Search className="w-4 h-4"/> Search Maps
                  </button>
                </div>
              </div>
            </div>
          </div>
          <div className="h-[400px] bg-zinc-200 rounded-3xl overflow-hidden border border-zinc-200 dark:border-zinc-800 shadow-inner">
            <iframe 
              src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15000000!2d72!3d22!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x30635ff06b92b791%3A0xd78c4fa1854213a6!2sIndia!5e0!3m2!1sen!2sin!4v1715000000000!5m2!1sen!2sin" 
              width="100%" 
              height="100%" 
              style={{border: 0}} 
              allowFullScreen 
              loading="lazy" 
              referrerPolicy="no-referrer-when-downgrade"
            ></iframe>
          </div>
        </div>
      </section>

      {/* WHY VOTE SECTION */}
      <section className="py-20 bg-[#FF671F]/5 dark:bg-[#FF671F]/10 border-t border-[#FF671F]/10">
        <div className="max-w-4xl mx-auto px-4 text-center">
          <h2 className="text-3xl font-bold mb-6 text-[#FF671F]">Why Vote?</h2>
          <p className="text-xl text-zinc-700 dark:text-zinc-300 leading-relaxed mb-8 max-w-2xl mx-auto">
            Voting is not just a right, it is your responsibility. Every single vote counts towards shaping the future of our democracy, deciding the policies that affect your daily life, and ensuring that your voice is truly heard. Be the change you want to see.
          </p>
          <button 
            onClick={() => shareToWhatsApp("Voting is not just a right, it is your responsibility. Every single vote counts towards shaping the future of our democracy. Be the change you want to see! Join me and get ready to vote. 🇮🇳 #ElectionSaathi")}
            className="inline-flex items-center gap-2 bg-[#046A38] text-white px-6 py-3 rounded-full hover:bg-[#03522b] font-medium transition-colors shadow-sm"
          >
            <Share2 className="w-5 h-5" /> Share this Message
          </button>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="bg-zinc-100 dark:bg-zinc-900 border-t border-zinc-200 dark:border-zinc-800 py-12 text-center text-zinc-500">
        <p className="mb-2">Election Saathi — Built to help India vote.</p>
        <p className="text-xs">Not affiliated with the Election Commission of India. Always cross-check official information at <a href="https://eci.gov.in" target="_blank" className="underline hover:text-zinc-800 dark:hover:text-zinc-300">eci.gov.in</a>.</p>
      </footer>
    </div>
  );
}
